[phases.setup]
nixPkgs = ["pandoc", "curl"]

[phases.install]
cmds = [
  "curl -fsSL https://github.com/pgaskin/kepubify/releases/latest/download/kepubify-linux-64bit -o /usr/local/bin/kepubify && chmod +x /usr/local/bin/kepubify",
  "npm ci"
]
